### PR TITLE
fix: Possible fix for displaying grumpy balance

### PR DESCRIPTION
**Pull request by lumtwj**
Possible fix for #2 

Seems like the balance are not shown because of string locale. Will need your help to test if it works since I can't replicate the problem.

### CODE REVIEW

**Comment by grumpyfinance** [comment]
It seems that didn't fix the issue.  It only shows the usd value, price and market cap. The grumpy Balance shows as 0 for a split second when you refresh it.

**Comment by grumpyfinance** [comment]
So we know what the issue is. It got fixed when I changed the language of chrome to en-us. Is there a way to go around that?

**Comment by lumtwj** [comment]
May I know what language are you previously on? I need to know so that I can do further testing to ensure the fix works.

**Comment by grumpyfinance** [comment]
Well, I asked the core group and it worked for basically all of them but didn't work for me and another one since we use Finnish language.

**Pull request merged**
